[general]
import = [
    "~/.config/alacritty/themes/themes/enfocado_dark.toml"
]

[font]
normal = { family = "Maple Mono NF", style = "Regular" }

[window]
dimensions = { columns = 130, lines = 30 }
padding = { x = 8, y = 8 }

[terminal]
shell = "/usr/bin/zellij"

[keyboard]
bindings = [
  { key = "Escape", mods = "Shift", action = "ToggleViMode" }
]

[mouse]
bindings = [
  { mouse = "Right", mods = "Shift", action = "Paste" },
]



