[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]

[font]
normal = { family = "Maple Mono NF", style = "Regular" }

[window]
dimensions = { columns = 130, lines = 30 }
padding = { x = 8, y = 8 }

[terminal]
shell = { program = "/usr/bin/zellij", args = ["attach", "puting"] }

[keyboard]
bindings = [{ key = "Escape", mods = "Shift", action = "ToggleViMode" }]

[mouse]
bindings = [{ mouse = "Right", mods = "Shift", action = "Paste" }]
